import json
from pathlib import Path
m=[{'key':'base','label':'BASE','accent':'base','description':'Broken or unstructured baseline behavior'},{'key':'sft','label':'SFT','accent':'sft','description':'Format-correct but wasteful behavior'},{'key':'grpo','label':'GRPO','accent':'grpo','description':'Targeted, restrained, evidence-driven behavior'}]
D=lambda v,c,t,o,s,r,rc,b,cf,e,sm,rt,n:{'verdict':v,'correct':c,'tool_calls_used':t,'optimal_tool_calls':o,'steps':s,'restraint':r,'recovery':rc,'behaviors_detected':b,'confidence':cf,'evidence_count':e,'summary':sm,'raw_trace':rt,'nodes':n}
N=lambda i,tp,ti,sm,ct,dc=None,st=None:{k:v for k,v in {'id':i,'type':tp,'title':ti,'summary':sm,'content':ct,'decision':dc,'status':st}.items() if v is not None}
T=[]
T.append({'id':'incident-triage','title':'Production Incident Triage','category':'Incident Triage','difficulty':'Hard','icon':'activity','prompt':'500 errors spiked on /api/checkout after the 14:05 deploy. Recommend rollback, hotfix, or no action.','traces':{
'base':D('fail',False,0,4,3,'n/a','none',['raw json output'],'low',0,'Malformed tool output, no answer','<think>I will inspect logs.</think>\n{"tool":"log_search"}',[N('b1','think','Loose intent','Knows logs matter.','I will inspect logs.','Call log search'),N('b2','error','Malformed output','Raw JSON, not a tool tag.','{"tool":"log_search"}','','Not executed'),N('b3','failure_terminal','Failed loop','Never returns an answer.','Generation ended at max steps.','', 'Failure')]),
'sft':D('partial',False,6,4,8,'weak','n/a',['broad queries','over-tooling'],'medium',4,'Right format, wrong action','<think>Check logs, deploys, flags, and runbook.</think>\n<tool_call>{"name":"log_search","arguments":{"query":"checkout"}}</tool_call>\n<observation>Many checkout errors.</observation>\n<answer>Rollback.</answer>',[N('s1','think','Broad plan','Touches everything too early.','Check logs, deploys, flags, and runbook.','Search broad logs'),N('s2','tool_call','Search logs','Query is too broad.','log_search(query="checkout")','', 'Executed'),N('s3','observation','Noisy result','Gets errors but weak scope info.','Many checkout errors, some on custom-pricing orgs.'),N('s4','tool_call','Read runbook','Reads criteria late.','read_spec(doc="incident runbook")','', 'Executed'),N('s5','warning_terminal','Partial answer','Structured, but recommends rollback.','Recommend rollback after the deploy.','', 'Partial')]),
'grpo':D('correct',True,4,4,8,'strong','strong',['targeted query','runbook citation','flag mitigation'],'high',4,'Targeted logs, deploy check, runbook rule, flag mitigation','<think>Decide whether impact is broad or isolated first.</think>\n<tool_call>{"name":"log_search","arguments":{"query":"NoneType has no attribute price","service":"checkout","level":"ERROR"}}</tool_call>\n<observation>All errors are custom-pricing orgs.</observation>\n<answer>Hotfix and disable new_checkout_flow.</answer>',[N('g1','think','Scope first','Uses rollback criteria before acting.','Decide whether impact is broad or isolated first.','Search targeted errors'),N('g2','tool_call','Search targeted logs','Looks for the exact signature.','log_search(query="NoneType has no attribute price", service="checkout", level="ERROR")','', 'Executed'),N('g3','observation','Impact pattern','Issue is isolated to custom-pricing orgs.','All errors are from custom-pricing orgs.'),N('g4','tool_call','Read runbook','Pulls the authority for rollback vs hotfix.','read_spec(doc="incident runbook")','', 'Executed'),N('g5','answer','Hotfix verdict','Correctly recommends hotfix plus flag disable.','Recommend HOTFIX, not rollback. Disable new_checkout_flow and patch custom pricing path.','', 'Correct')])
}})
T.append({'id':'spec-audit','title':'Spec Compliance Audit','category':'Spec Audit','difficulty':'Hard','icon':'shield','prompt':'Audit the auth middleware against the API Security Spec.','traces':{
'base':D('fail',False,0,2,2,'n/a','none',['ungrounded security claims'],'low',0,'General security language, no audit','<think>Middleware should be secure.</think>\n<answer>There may be security issues.</answer>',[N('b1','think','Generic security','No rules or code inspection.','Middleware should be secure.'),N('b2','failure_terminal','Ungrounded answer','No evidence or citations.','There may be security issues.','', 'Failure')]),
'sft':D('partial',False,2,2,5,'medium','n/a',['reads both sources','misses violations'],'medium',2,'Finds only part of the problem set','<think>Read spec and middleware.</think>\n<tool_call>{"name":"read_spec","arguments":{"doc":"API Security Spec"}}</tool_call>\n<observation>AUTH-001..004 apply.</observation>\n<answer>Found weak algorithm handling and token storage issue.</answer>',[N('s1','think','Read sources','Starts correctly.','Read spec and middleware.','Read spec'),N('s2','tool_call','Read spec','Gets auth rules.','read_spec(doc="API Security Spec")','', 'Executed'),N('s3','observation','Rule surface','Rules AUTH-001..004 apply.','AUTH-001..004 apply.'),N('s4','tool_call','Read middleware','Inspects code.','read_code(path="auth/middleware.py")','', 'Executed'),N('s5','warning_terminal','Partial audit','Misses expiry and hardcoded key.','Found weak algorithm handling and token storage issue.','', 'Partial')]),
'grpo':D('correct',True,2,2,7,'strong','n/a',['systematic rule check','exact citations'],'high',4,'Finds all four auth violations with citations','<think>Enumerate each AUTH rule first so the audit is exhaustive.</think>\n<tool_call>{"name":"read_spec","arguments":{"doc":"API Security Spec"}}</tool_call>\n<observation>AUTH-001..004 define algorithm, key, expiry, and token-storage rules.</observation>\n<answer>AUTH-001, AUTH-002, AUTH-003, AUTH-004 all violated.</answer>',[N('g1','think','Exhaustive audit','Builds a checklist from the spec.','Enumerate each AUTH rule first so the audit is exhaustive.','Read spec'),N('g2','tool_call','Read spec','Pulls all audit rules.','read_spec(doc="API Security Spec")','', 'Executed'),N('g3','observation','Checklist','AUTH-001..004 cover algorithm, key, expiry, and token storage.','AUTH-001..004 define algorithm, key, expiry, and token-storage rules.'),N('g4','tool_call','Read middleware','Checks implementation against each rule.','read_code(path="auth/middleware.py")','', 'Executed'),N('g5','answer','Complete audit','Cites all four violations.','Violations: AUTH-001 algorithm policy, AUTH-002 hardcoded key, AUTH-003 720hr expiry, AUTH-004 token stored in g.session_token.','', 'Correct')])
}})
T.append({'id':'customer-bug','title':'Customer Bug Reproduction','category':'Bug Repro','difficulty':'Hard','icon':'bug','prompt':'Exports fail for orgs with custom roles like billing-admin. Find the root cause.','traces':{
'base':D('fail',False,0,3,2,'n/a','none',['no reproduction'],'low',0,'Speculates about permissions, no repro','<think>Exports often fail because of permissions.</think>\n<answer>Check export permissions.</answer>',[N('b1','think','Speculation','No targeted reproduction.','Exports often fail because of permissions.'),N('b2','failure_terminal','No diagnosis','No root cause identified.','Check export permissions.','', 'Failure')]),
'sft':D('partial',True,5,3,6,'weak','n/a',['finds bug','extra motion'],'medium',3,'Finds the hardcoded role list after extra searches','<think>Search exports, logs, and related code.</think>\n<tool_call>{"name":"codebase_search","arguments":{"query":"export"}}</tool_call>\n<observation>Found export.py and tests.</observation>\n<answer>export.py hardcodes allowed roles.</answer>',[N('s1','think','Search-heavy plan','Knows code matters, but adds noise.','Search exports, logs, and related code.','Search codebase'),N('s2','tool_call','Search exports','Finds the right files.','codebase_search(query="export")','', 'Executed'),N('s3','observation','Relevant files','export.py and tests are relevant.','Found export.py and tests.'),N('s4','tool_call','Read export.py','Finally inspects implementation.','read_code(path="export.py")','', 'Executed'),N('s5','warning_terminal','Correct but noisy','Identifies the hardcoded role list.','export.py hardcodes allowed roles and excludes billing-admin.','', 'Partial')]),
'grpo':D('correct',True,3,3,7,'strong','n/a',['reproduce first','reads test'],'high',3,'Reproduces the failure, uses the test as the contract, then isolates the hardcoded role list','<think>Reproduce first, then read the failing test before opening implementation.</think>\n<tool_call>{"name":"run_tests","arguments":{"target":"tests/test_export.py::test_custom_role_export"}}</tool_call>\n<observation>billing-admin fails with ExportNotAuthorized.</observation>\n<answer>The bug is a hardcoded role allowlist in export.py.</answer>',[N('g1','think','Reproduce first','Uses the failing test as the contract.','Reproduce first, then read the failing test before opening implementation.','Run targeted test'),N('g2','tool_call','Run targeted test','Gets the exact failure mode.','run_tests(target="tests/test_export.py::test_custom_role_export")','', 'Executed'),N('g3','observation','Failure reproduced','billing-admin is rejected.','billing-admin fails with ExportNotAuthorized.'),N('g4','tool_call','Read failing test','Reads expected behavior before code.','read_code(path="tests/test_export.py")','', 'Executed'),N('g5','answer','Root cause','Hardcoded allowlist ignores org-derived custom roles.','The bug is a hardcoded role allowlist in export.py.','', 'Correct')])
}})
T.append({'id':'data-discrepancy','title':'Data Discrepancy Investigation','category':'Data Discrepancy','difficulty':'Medium','icon':'database','prompt':'Dashboard says $12,450.49 and warehouse says $11,705.48. Determine the cause.','traces':{
'base':D('fail',False,0,3,2,'n/a','none',['guessing'],'low',0,'Guesses about rounding','<think>It is probably rounding.</think>\n<answer>Likely rounding or sync lag.</answer>',[N('b1','think','Guess','No source inspection.','It is probably rounding.'),N('b2','failure_terminal','Unsupported answer','No evidence for the claim.','Likely rounding or sync lag.','', 'Failure')]),
'sft':D('partial',False,2,3,5,'medium','n/a',['definition reading','no resolution'],'medium',2,'Finds differing definitions but does not resolve the numeric delta','<think>Read both definitions.</think>\n<tool_call>{"name":"read_spec","arguments":{"doc":"dashboard revenue definition"}}</tool_call>\n<observation>Dashboard includes tax and shipping.</observation>\n<answer>The systems define revenue differently.</answer>',[N('s1','think','Definitions first','Good start, but stops early.','Read both definitions.','Read dashboard definition'),N('s2','tool_call','Read dashboard definition','Gets displayed-gross scope.','read_spec(doc="dashboard revenue definition")','', 'Executed'),N('s3','observation','Dashboard scope','Includes tax and shipping.','Dashboard includes tax and shipping.'),N('s4','tool_call','Read warehouse definition','Gets reporting scope.','read_spec(doc="warehouse revenue definition")','', 'Executed'),N('s5','warning_terminal','Incomplete resolution','Does not quantify the delta.','The systems define revenue differently.','', 'Partial')]),
'grpo':D('correct',True,3,3,7,'strong','n/a',['definition-first','quantifies delta'],'high',3,'Explains the exact delta and recommends the correct reporting source','<think>Read definitions first, then verify the numeric delta.</think>\n<tool_call>{"name":"read_spec","arguments":{"doc":"dashboard revenue definition"}}</tool_call>\n<observation>Dashboard includes taxes and shipping.</observation>\n<tool_call>{"name":"calculator","arguments":{"expression":"12450.49 - 11705.48"}}</tool_call>\n<observation>745.01</observation>\n<answer>The delta is taxes plus shipping. Use the warehouse number for reporting.</answer>',[N('g1','think','Resolve by definition','Uses semantics before arithmetic.','Read definitions first, then verify the numeric delta.','Read both definitions'),N('g2','tool_call','Read dashboard definition','Gets included fields.','read_spec(doc="dashboard revenue definition")','', 'Executed'),N('g3','observation','Definition gap','Dashboard includes taxes and shipping; warehouse excludes them.','Dashboard includes taxes and shipping; warehouse excludes them.'),N('g4','tool_call','Quantify delta','Checks the exact number.','calculator(expression="12450.49 - 11705.48")','', 'Executed'),N('g5','answer','Resolved discrepancy','Connects the delta to the definition gap.','The delta is taxes plus shipping. Use the warehouse number for reporting.','', 'Correct')])
}})
T.append({'id':'ci-fix','title':'CI Failure -> Fix','category':'CI Fix','difficulty':'Hard','icon':'wrench','prompt':'Checkout test suite has a failing test after the latest deploy. Identify the root cause.','traces':{
'base':D('fail',False,0,3,2,'n/a','none',['no execution'],'low',0,'Generic advice, no debugging loop','<think>Checkout tests fail when logic changes.</think>\n<answer>Inspect the deploy and tests.</answer>',[N('b1','think','Generic debugging','No execution or inspection.','Checkout tests fail when logic changes.'),N('b2','failure_terminal','Non-answer','Suggests work instead of doing it.','Inspect the deploy and tests.','', 'Failure')]),
'sft':D('partial',True,5,3,6,'weak','n/a',['broad suite','extra motion'],'medium',3,'Finds missing org discount logic but takes a wider path than needed','<think>Run checkout tests and inspect the code path.</think>\n<tool_call>{"name":"run_tests","arguments":{"target":"tests/test_checkout.py"}}</tool_call>\n<observation>test_checkout_org_discount fails.</observation>\n<answer>Missing org discount logic in checkout.py.</answer>',[N('s1','think','Broad test run','Runs wider than needed.','Run checkout tests and inspect the code path.','Run test file'),N('s2','tool_call','Run checkout tests','Gets the right failing area, but broadly.','run_tests(target="tests/test_checkout.py")','', 'Executed'),N('s3','observation','Failing case','test_checkout_org_discount fails.','test_checkout_org_discount fails.'),N('s4','tool_call','Read checkout.py','Finds the bug.','read_code(path="checkout.py")','', 'Executed'),N('s5','warning_terminal','Correct but noisy','Finds the missing org discount path.','Missing org discount logic in checkout.py.','', 'Partial')]),
'grpo':D('correct',True,3,3,7,'strong','n/a',['targeted test','reads assertion'],'high',3,'Runs the exact failing test, reads the expected behavior, then isolates the missing discount logic','<think>Run the exact failing test, then inspect the assertion before reading implementation.</think>\n<tool_call>{"name":"run_tests","arguments":{"target":"tests/test_checkout.py::test_checkout_org_discount"}}</tool_call>\n<observation>Expected 91.00, got 100.00.</observation>\n<answer>The total path never subtracts org_discount.</answer>',[N('g1','think','Narrow reproduction','Starts from the smallest failing unit.','Run the exact failing test, then inspect the assertion before reading implementation.','Run targeted test'),N('g2','tool_call','Run failing test','Gets the exact mismatch.','run_tests(target="tests/test_checkout.py::test_checkout_org_discount")','', 'Executed'),N('g3','observation','Assertion mismatch','Discounted total was not applied.','Expected 91.00, got 100.00.'),N('g4','tool_call','Read failing test','Uses the test as the contract.','read_code(path="tests/test_checkout.py")','', 'Executed'),N('g5','answer','Root cause','checkout.py never subtracts org_discount before tax.','The total path never subtracts org_discount.','', 'Correct')])
}})
T.append({'id':'schema-migration','title':'Schema Migration Planning','category':'Schema Migration','difficulty':'Hard','icon':'git-branch','prompt':'Rename customer_id to account_id across the service without breaking compatibility.','traces':{
'base':D('fail',False,0,4,2,'n/a','none',['generic advice'],'low',0,'Generic ALTER TABLE advice, no repo plan','<think>Rename the column and update code.</think>\n<answer>Use ALTER TABLE and rename references.</answer>',[N('b1','think','Generic migration thought','No compatibility strategy.','Rename the column and update code.'),N('b2','failure_terminal','Unsafe plan','No phased rollout.','Use ALTER TABLE and rename references.','', 'Failure')]),
'sft':D('partial',False,1,4,4,'medium','n/a',['reference search','misses guide'],'medium',1,'Finds references but misses the migration guide and phased strategy','<think>Search for customer_id references.</think>\n<tool_call>{"name":"codebase_search","arguments":{"query":"customer_id"}}</tool_call>\n<observation>Found models, api, and migration references.</observation>\n<answer>Rename customer_id to account_id everywhere.</answer>',[N('s1','think','Reference search','Good start, but no migration policy.','Search for customer_id references.','Search codebase'),N('s2','tool_call','Search references','Maps some affected files.','codebase_search(query="customer_id")','', 'Executed'),N('s3','observation','Reference map','Models, api, and migration files are affected.','Found models, api, and migration references.'),N('s4','warning_terminal','Incomplete plan','Direct rename misses compatibility phases.','Rename customer_id to account_id everywhere.','', 'Partial')]),
'grpo':D('correct',True,4,4,8,'strong','n/a',['blast-radius map','reads guide','phased plan'],'high',4,'Builds a safe three-phase rename plan from references plus the migration guide','<think>Map references first, then read the rename guide so the plan preserves compatibility.</think>\n<tool_call>{"name":"codebase_search","arguments":{"query":"customer_id"}}</tool_call>\n<observation>Models, serializers, api, tests, and migration 003 are affected.</observation>\n<answer>Add account_id and dual-write, backfill, migrate readers, then remove customer_id after the compatibility window.</answer>',[N('g1','think','Compatibility-first','Starts with blast radius and rollout constraints.','Map references first, then read the rename guide so the plan preserves compatibility.','Search references'),N('g2','tool_call','Search references','Builds the blast-radius map.','codebase_search(query="customer_id")','', 'Executed'),N('g3','observation','Affected surfaces','Models, serializers, api, tests, and migration 003 are affected.','Models, serializers, api, tests, and migration 003 are affected.'),N('g4','tool_call','Read migration guide','Pulls the repo strategy.','read_spec(doc="migration guide rename strategy")','', 'Executed'),N('g5','answer','Phased plan','Returns a compatibility-safe rollout plan.','Add account_id and dual-write, backfill, migrate readers, then remove customer_id after the compatibility window.','', 'Correct')])
}})
T.append({'id':'conflicting-evidence','title':'Conflicting Evidence Resolution','category':'Conflict Resolution','difficulty':'Hard','icon':'git-merge','prompt':'Spec says 1hr expiry, code says 720hr. Which should win and what should change?','traces':{
'base':D('fail',False,0,3,2,'n/a','none',['unresolved conflict'],'low',0,'Sees the conflict but does not resolve it','<think>The spec and code disagree.</think>\n<answer>There is a conflict that should be investigated.</answer>',[N('b1','think','Conflict noticed','No authority rule or test check.','The spec and code disagree.'),N('b2','failure_terminal','No resolution','Acknowledges mismatch without deciding.','There is a conflict that should be investigated.','', 'Failure')]),
'sft':D('partial',False,2,3,5,'medium','n/a',['reads both sources','no authority decision'],'medium',2,'Reads spec and code but only reports the conflict','<think>Read the spec and the token code.</think>\n<tool_call>{"name":"read_spec","arguments":{"doc":"AUTH-003"}}</tool_call>\n<observation>Expiry must be <= 1 hour.</observation>\n<answer>The spec and code conflict on token expiry.</answer>',[N('s1','think','Gather both sides','Collects evidence but no decision rule.','Read the spec and the token code.','Read spec'),N('s2','tool_call','Read AUTH-003','Gets the requirement.','read_spec(doc="AUTH-003")','', 'Executed'),N('s3','observation','Spec requirement','Expiry must be <= 1 hour.','Expiry must be <= 1 hour.'),N('s4','tool_call','Read token code','Confirms mismatch.','read_code(path="auth/tokens.py")','', 'Executed'),N('s5','warning_terminal','Conflict only','Does not resolve authority or fix.','The spec and code conflict on token expiry.','', 'Partial')]),
'grpo':D('correct',True,3,3,7,'strong','n/a',['authority-first','test-backed recommendation'],'high',3,'Treats the spec as authoritative, confirms the mismatch, and uses tests to justify the fix','<think>Read the spec first because it is authoritative, then confirm implementation and test behavior.</think>\n<tool_call>{"name":"read_spec","arguments":{"doc":"AUTH-003"}}</tool_call>\n<observation>Expiry must be <= 1 hour.</observation>\n<answer>The spec should win. Change create_token to expires_hours=1.</answer>',[N('g1','think','Authority-first','Chooses the decision rule before gathering everything.','Read the spec first because it is authoritative, then confirm implementation and test behavior.','Read spec'),N('g2','tool_call','Read AUTH-003','Gets the authoritative requirement.','read_spec(doc="AUTH-003")','', 'Executed'),N('g3','observation','Authoritative rule','Expiry must be <= 1 hour.','Expiry must be <= 1 hour.'),N('g4','tool_call','Run expiry tests','Uses tests as downstream evidence.','run_tests(target="tests/test_auth_expiry.py")','', 'Executed'),N('g5','answer','Resolution','Spec wins and code should change.','The spec should win. Change create_token to expires_hours=1.','', 'Correct')])
}})
T.append({'id':'restraint-409','title':'Restraint: HTTP Conflict','category':'Restraint','difficulty':'Easy','icon':'zap','prompt':'What HTTP status code should be returned for a business logic conflict?','traces':{
'base':D('partial',True,0,0,2,'medium','n/a',['correct answer','no structure'],'medium',0,'Gets the answer but with no useful reasoning surface','<answer>409 Conflict.</answer>',[N('b1','think','Recall','Correct from pretraining, low observability.','This is a standard HTTP status question.'),N('b2','warning_terminal','Correct but opaque','Gets the answer without trace value.','409 Conflict.','', 'Correct')]),
'sft':D('partial',True,1,0,4,'weak','n/a',['unnecessary tool use'],'medium',1,'Uses docs for a trivial question','<think>Verify in docs.</think>\n<tool_call>{"name":"search_docs","arguments":{"query":"HTTP business logic conflict status"}}</tool_call>\n<observation>409 Conflict.</observation>\n<answer>409 Conflict.</answer>',[N('s1','think','Over-verification','Treats direct recall as retrieval.','Verify in docs.','Search docs'),N('s2','tool_call','Search docs','Unnecessary tool call.','search_docs(query="HTTP business logic conflict status")','', 'Executed'),N('s3','observation','Docs confirm 409','The tool confirms what should already be known.','409 Conflict.'),N('s4','warning_terminal','Correct but unrestrained','Answer is right, process is wasteful.','409 Conflict.','', 'Unnecessary tool')]),
'grpo':D('correct',True,0,0,2,'strong','n/a',['answers directly'],'high',0,'Answers directly with zero tool calls','<think>This is standard protocol knowledge. No tool is needed.</think>\n<answer>409 Conflict.</answer>',[N('g1','think','Restraint','Recognizes no tools are justified.','This is standard protocol knowledge. No tool is needed.','Answer directly'),N('g2','answer','Direct answer','Returns the correct status immediately.','409 Conflict.','', 'Correct')])
}})
T.append({'id':'restraint-jwt','title':'Restraint: JWT Claims','category':'Restraint','difficulty':'Easy','icon':'key','prompt':'What is the difference between JWT sub and iss?','traces':{
'base':D('partial',True,0,0,2,'medium','n/a',['correct answer'],'medium',0,'Correct but not structured','<answer>sub is subject, iss is issuer.</answer>',[N('b1','think','Recall','Knows the distinction, low observability.','This is a standard JWT claim question.'),N('b2','warning_terminal','Correct but opaque','Right answer, weak trace.','sub is subject, iss is issuer.','', 'Correct')]),
'sft':D('partial',True,1,0,4,'weak','n/a',['unnecessary retrieval'],'medium',1,'Searches docs for a basic JWT distinction','<think>Search auth docs to verify.</think>\n<tool_call>{"name":"search_docs","arguments":{"query":"JWT sub vs iss"}}</tool_call>\n<observation>sub=subject, iss=issuer.</observation>\n<answer>sub is the subject; iss is the issuer.</answer>',[N('s1','think','Unneeded lookup','Uses retrieval for basic knowledge.','Search auth docs to verify.','Search docs'),N('s2','tool_call','Search auth docs','Tool usage is unnecessary.','search_docs(query="JWT sub vs iss")','', 'Executed'),N('s3','observation','Claim meanings','Tool returns the obvious mapping.','sub=subject, iss=issuer.'),N('s4','warning_terminal','Correct but wasteful','Answer is right, process is not restrained.','sub is the subject; iss is the issuer.','', 'Unnecessary tool')]),
'grpo':D('correct',True,0,0,2,'strong','n/a',['direct answer'],'high',0,'Answers directly with zero tool calls','<think>This is direct JWT knowledge. No retrieval is needed.</think>\n<answer>sub is the subject claim; iss is the issuer claim.</answer>',[N('g1','think','Direct knowledge','Recognizes no tools are needed.','This is direct JWT knowledge. No retrieval is needed.','Answer directly'),N('g2','answer','Direct answer','Returns the distinction immediately.','sub is the subject claim; iss is the issuer claim.','', 'Correct')])
}})
T.append({'id':'restraint-o1','title':'Restraint: Hash Table Lookup','category':'Restraint','difficulty':'Easy','icon':'hash','prompt':'What is the average-case time complexity of hash table lookup?','traces':{
'base':D('partial',True,0,0,2,'medium','n/a',['correct answer'],'medium',0,'Correct but without useful structure','<answer>O(1) on average.</answer>',[N('b1','think','Recall','Basic DS knowledge, low trace value.','This is a standard data-structures question.'),N('b2','warning_terminal','Correct but opaque','Gets the answer without a real reasoning surface.','O(1) on average.','', 'Correct')]),
'sft':D('partial',True,1,0,4,'weak','n/a',['unnecessary retrieval'],'medium',1,'Searches docs before answering a trivial complexity question','<think>Verify complexity in docs.</think>\n<tool_call>{"name":"search_docs","arguments":{"query":"hash table average lookup complexity"}}</tool_call>\n<observation>Average lookup is O(1).</observation>\n<answer>O(1) average-case lookup.</answer>',[N('s1','think','Over-checking','Uses retrieval for instant recall.','Verify complexity in docs.','Search docs'),N('s2','tool_call','Search docs','Unnecessary tool call.','search_docs(query="hash table average lookup complexity")','', 'Executed'),N('s3','observation','Complexity confirmed','Docs confirm O(1).','Average lookup is O(1).'),N('s4','warning_terminal','Correct but over-tooled','Answer is right, process is wasteful.','O(1) average-case lookup.','', 'Unnecessary tool')]),
'grpo':D('correct',True,0,0,2,'strong','n/a',['restraint'],'high',0,'Answers directly with zero tools','<think>This is standard data-structure knowledge. No tool is needed.</think>\n<answer>O(1) average-case lookup.</answer>',[N('g1','think','No tool needed','Chooses not to retrieve obvious knowledge.','This is standard data-structure knowledge. No tool is needed.','Answer directly'),N('g2','answer','Direct answer','Returns the expected answer immediately.','O(1) average-case lookup.','', 'Correct')])
}})
Path(r'D:\Codetune\playground\data').mkdir(parents=True, exist_ok=True)
Path(r'D:\Codetune\playground\data\v2_traces.json').write_text(json.dumps({'version':'2.0','models':m,'tasks':T},indent=2),encoding='utf-8')
print('wrote',len(T),'tasks')
